package Presentation.View.Main;

import java.util.ArrayList;
import java.util.Arrays;

public class PlatformNames extends ArrayList<String> {

    public PlatformNames() {
        super(Arrays.asList(
                "3DO Interactive Multiplayer",
                "Acorn Archimedes",
                "Acorn Electron",
                "Amiga",
                "Amiga CD32",
                "Amstrad CPC",
                "Amstrad PCW",
                "Android",
                "Apple II",
                "Apple IIGS",
                "Arcade",
                "Atari 2600",
                "Atari 5200",
                "Atari 7800",
                "Atari 8-bit",
                "Atari Jaguar",
                "Atari Lynx",
                "Atari ST/STE",
                "BBC Microcomputer System",
                "Bally Astrocade",
                "BlackBerry OS",
                "Blu-ray Player",
                "Call-A-Computer time-shared mainframe computer system",
                "ColecoVision",
                "Commodore 16",
                "Commodore C64/128",
                "Commodore CDTV",
                "Commodore PET",
                "Commodore Plus/4",
                "Commodore VIC-20",
                "Dreamcast",
                "Epoch Cassette Vision",
                "Evercade",
                "FM Towns",
                "FM-7",
                "Fairchild Channel F",
                "Family Computer",
                "Family Computer Disk System",
                "Game Boy",
                "Game Boy Advance",
                "Game Boy Color",
                "Google Stadia",
                "Intellivision",
                "Legacy Mobile Device",
                "Linux",
                "MSX",
                "MSX2",
                "Mac",
                "N-Gage",
                "NEC PC-6000 Series",
                "Neo Geo AES",
                "Neo Geo CD",
                "Neo Geo MVS",
                "Neo Geo Pocket Color",
                "New Nintendo 3DS",
                "Nintendo 3DS",
                "Nintendo 64",
                "Nintendo DS",
                "Nintendo DSi",
                "Nintendo Entertainment System (NES)",
                "Nintendo GameCube",
                "Nintendo Switch",
                "Nuon",
                "OOParts",
                "Oculus Quest",
                "Oculus Quest 2",
                "Oculus VR",
                "Odyssey",
                "Ouya",
                "PC (Microsoft Windows)",
                "PC DOS",
                "PC Engine SuperGrafx",
                "PC-8801",
                "PC-98",
                "Philips CD-i",
                "Philips Videopac G7000",
                "PlayStation",
                "PlayStation 2",
                "PlayStation 3",
                "PlayStation 4",
                "PlayStation 5",
                "PlayStation Portable",
                "PlayStation VR",
                "PlayStation Vita",
                "Playdate",
                "SG-1000",
                "Satellaview",
                "Sega CD",
                "Sega Game Gear",
                "Sega Master System",
                "Sega Mega Drive/Genesis",
                "Sega Saturn",
                "Sharp X1",
                "Sharp X68000",
                "SteamVR",
                "Super Famicom",
                "Super Nintendo Entertainment System (SNES)",
                "TRS-80",
                "TRS-80 Color Computer",
                "Texas Instruments TI-99",
                "TurboGrafx-16/PC Engine",
                "Turbografx-16/PC Engine CD",
                "Vectrex",
                "Web browser",
                "Wii",
                "Wii U",
                "Windows Mixed Reality",
                "Windows Phone",
                "WonderSwan",
                "WonderSwan Color",
                "Xbox",
                "Xbox 360",
                "Xbox One",
                "Xbox Series X|S",
                "ZX Spectrum",
                "Zeebo",
                "iOS"
        ));
    }
}
