name: CI

on:
  push:
    branches:
    - main
    - prototipo_2_tests_jbehave
  pull_request:
    branches:
    - main
    - prototipo_2_tests_jbehave
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1 - Checkout rama de tests
        uses: actions/checkout@v3
        with:
          ref: 'prototipo_2_tests_jbehave'

      - name: Paso 2.1 - Preparar JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Paso 2.2 - Comprobar version de Java
        run: java -version
        
      - name: Paso 3.1 - Compilar/Build el proyecto de Java con Maven
        run: |
            cd Codigo/Prototipo_mongDB_1
            mvn clean -B package --file pom.xml
            mkdir build && cp target/*.jar build
            
      - name: Paso 3.2 - Comprobar que se ha compilado el proyecto correctamente
        run: |
            cd Codigo/Prototipo_mongDB_1/build
            ls | grep .jar
            
      - name: Paso 4.1 - Ejecutar tests unitarios
        run: |
             cd Codigo/Prototipo_mongDB_1
             mvn -Dtest=UnitTest test
             
      - name: Paso 4.2 - Ejecutar tests de integracion
        if: success()
        run: |
             cd Codigo/Prototipo_mongDB_1
             mvn -Dtest=IntegrationTest test
        
      - name: Paso 5.1 - Subir el proyecto compilado como un artefacto
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: PrototipoMongoDB
          path: Codigo/Prototipo_mongDB_1/build
